[workspace]
members = [
  "conformance",
  "prost",
  "prost-build",
  "prost-derive",
  "prost-types",
  "protobuf",
  "tests",
  "tests-2015",
  "tests-no-std",
  "tests/single-include",
]

exclude = [
  # The fuzz crate can't be compiled or tested without the 'cargo fuzz' command,
  # so exclude it from normal builds.
  "fuzz",
  # Same counts for the afl fuzz targets
  "afl",
]

resolver = "2"

[workspace.dependencies]
anyhow = { version = "1.0.45", default-features = false }
bytes = { version = "1", default-features = false }
cfg-if = "1"
criterion = { version = "0.4", default-features = false }
diff = "0.1"
env_logger = { version = "0.10", default-features = false }
heck = ">=0.4, <=0.5"
itertools = { version = ">=0.10, <=0.12", default-features = false }
libz-sys = "1.1, <1.1.7"
log = "0.4.4"
multimap = { version = ">=0.8, <=0.10", default-features = false }
once_cell = "1.17.1"
petgraph = { version = "0.6", default-features = false }
prettyplease = "0.2"
proc-macro2 = "1"
proptest = "1"
pulldown-cmark = { version = "0.9.1", default-features = false }
pulldown-cmark-to-cmark = "10.0.1"
quote = "1"
rand = "0.8"
regex = { version = "1.8.1", default-features = false }
syn = "2"
tempfile = "3"

[profile.bench]
debug = true
