[workspace]
members = [
  "conformance",
  "prost",
  "prost-build",
  "prost-derive",
  "prost-types",
  "protobuf",
  "tests",
  "tests-2015",
  "tests-no-std",
  "tests/single-include",
]

exclude = [
  # The fuzz crate can't be compiled or tested without the 'cargo fuzz' command,
  # so exclude it from normal builds.
  "fuzz",
  # Same counts for the afl fuzz targets
  "afl",
]

resolver = "2"

[profile.bench]
debug = true
