[workspace]
members = [
  "conformance",
  "prost",
  "prost-build",
  "prost-derive",
  "prost-types",
  "protobuf",
  "tests",
  "tests-2015",
  "tests-no-std",
  "tests/single-include",
]

exclude = [
  # The fuzz crate can't be compiled or tested without the 'cargo fuzz' command,
  # so exclude it from normal builds.
  "fuzz",
  # Same counts for the afl fuzz targets
  "afl",
]

resolver = "2"

[workspace.package]
authors = [
  "Dan Burkert <dan@danburkert.com>",
  "Lucio Franco <luciofranco14@gmail.com>",
  "Casper Meijn <casper@meijn.net>",
  "Tokio Contributors <team@tokio.rs>",
]
repository = "https://github.com/tokio-rs/prost"

[profile.bench]
debug = true
