[package]
name = "prost-types"
readme = "README.md"
description = "Prost definitions of Protocol Buffers well known types."
version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
edition.workspace = true
rust-version.workspace = true

[lib]
doctest = false

[features]
default = ["std"]
std = ["prost/std"]
serde = ["prost/serde"]
any-v2 = ["std", "serde", "prost/serde-json", "dep:serde", "dep:erased-serde"]

[dependencies]
prost = { version = "0.13.4", path = "../prost", default-features = false, features = ["prost-derive"] }

erased-serde = { version = "0.4.3", optional = true }
serde = { version = "1.0.189", features = ["derive"], optional = true }

[dev-dependencies]
proptest = "1"

[lints.rust]
unexpected_cfgs = { level = "warn", check-cfg = ['cfg(kani)'] }
