[package]
name = "prost-types"
# NB: When modifying, also modify html_root_url in lib.rs
version = "0.3.1"
authors = ["Dan Burkert <dan@danburkert.com>"]
license = "Apache-2.0"
repository = "https://github.com/danburkert/prost"
documentation = "https://docs.rs/prost-types"
readme = "README.md"
description = "A Protocol Buffers implementation for the Rust Language."

[lib]
doctest = false
test = false

[dependencies]
bytes = "0.4"
prost = { version = "0.3.1", path = ".." }
prost-derive = { version = "0.3.1", path = "../prost-derive" }
