[package]
name = "prost-types"
version = "0.12.6"
authors.workspace = true
license.workspace = true
repository.workspace = true
readme = "README.md"
description = "Prost definitions of Protocol Buffers well known types."
edition = "2021"
rust-version = "1.70"

[lib]
doctest = false

[features]
default = ["std"]
std = ["prost/std"]

[dependencies]
prost = { version = "0.12.6", path = "../prost", default-features = false, features = ["prost-derive"] }

[dev-dependencies]
proptest = "1"
