[package]
name = "conformance"
version = "0.0.0"
authors.workspace = true
publish = false
edition = "2021"

[dependencies]
bytes = "1"
env_logger = { version = "0.11", default-features = false }
prost = { path = "../prost" }
protobuf = { path = "../protobuf" }
tests = { path = "../tests" }
