[package]
name = "conformance"
version = "0.0.0"
authors = [
    "Dan Burkert <dan@danburkert.com>",
    "Tokio Contributors <team@tokio.rs>",
]
publish = false
edition = "2018"

[dependencies]
bytes = "1"
env_logger = { version = "0.8", default-features = false }
log = "0.4"
prost = { path = ".." }
protobuf = { path = "../protobuf" }
tests = { path = "../tests" }
serde_json = { version="1.0" }
serde_path_to_error = "0.1"
