[package]
name = "prost-build"
# NB: When modifying, also modify html_root_url in lib.rs
version = "0.1.1"
authors = ["Dan Burkert <dan@danburkert.com>"]
license = "Apache-2.0"
repository = "https://github.com/danburkert/prost"
documentation = "https://docs.rs/prost-build"
readme = "README.md"
description = "A Protocol Buffers implementation for the Rust Language."

[dependencies]
bytes = "0.4"
env_logger = "0.4"
itertools = "0.6"
log = "0.3"
multimap = "0.3"
petgraph = "0.4"
prost = { path = ".." }
prost-types = { path = "../prost-types" }
tempdir = "0.3"

[build-dependencies]
curl = "0.4"
tempdir = "0.3"
zip = "0.2"
