[package]
name = "prost-build"
# NB: When modifying, also modify html_root_url in lib.rs
version = "0.2.3"
authors = ["Dan Burkert <dan@danburkert.com>"]
license = "Apache-2.0"
repository = "https://github.com/danburkert/prost"
documentation = "https://docs.rs/prost-build"
readme = "README.md"
description = "A Protocol Buffers implementation for the Rust Language."

[dependencies]
bytes = "0.4"
env_logger = "0.4"
heck = "0.3"
itertools = "0.7"
log = "0.4"
multimap = { version = "0.4", default-features = false }
petgraph = "0.4"
prost = { version = "0.2", path = ".." }
prost-types = { version = "0.2", path = "../prost-types" }
tempdir = "0.3"

[build-dependencies]
curl = "0.4"
tempdir = "0.3"
zip = "0.2"

[dev-dependencies]
env_logger = "0.4"
