[package]
name = "fuzz"
version = "0.0.0"
authors = [
    "Dan Burkert <dan@danburkert.com>",
    "Tokio Contributors <team@tokio.rs>",
]
publish = false
edition = "2018"

[package.metadata]
cargo-fuzz = true

[dependencies]
protobuf.workspace = true
tests.workspace = true

libfuzzer-sys.workspace = true

[[bin]]
name = "proto3"
path = "fuzzers/proto3.rs"

[[bin]]
name = "proto2"
path = "fuzzers/proto2.rs"
