[package]
name = "fuzz"
version = "0.0.0"
authors = ["Dan Burkert <dan@danburkert.com>"]
publish = false

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = { git = "https://github.com/rust-fuzz/libfuzzer-sys.git" }
protobuf = { path = "../protobuf" }
tests = { path = "../tests" }

[[bin]]
name = "proto3"
path = "fuzzers/proto3.rs"
