[package]
name = "fuzz"
version = "0.0.0"
publish = false
edition.workspace = true
authors.workspace = true

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = { git = "https://github.com/rust-fuzz/libfuzzer-sys.git" }
tests = { path = "../tests" }

[[bin]]
name = "proto3"
path = "fuzzers/proto3.rs"

[[bin]]
name = "proto2"
path = "fuzzers/proto2.rs"
