[package]
name = "fuzz"
version = "0.0.0"
authors = ["Dan Burkert <dan@danburkert.com>"]
publish = false
edition = "2018"

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = { git = "https://github.com/rust-fuzz/libfuzzer-sys.git" }
protobuf = { path = "../protobuf", default-features = false }
tests = { path = "../tests", default-features = false }

[[bin]]
name = "proto3"
path = "fuzzers/proto3.rs"

[[bin]]
name = "proto2"
path = "fuzzers/proto2.rs"

[features]
default = ["std"]
std = ["protobuf/std", "tests/std"]
