[package]
name = "protobuf"
version = "0.0.0"
authors = ["Dan Burkert <dan@danburkert.com>"]
publish = false

[build-dependencies]
cfg-if = "0.1"
curl = "0.4"
flate2 = "1.0"
tar = "0.4"
tempdir = "0.3"
