[package]
name = "prost-derive"
# NB: When modifying, also modify html_root_url in lib.rs
version = "0.3.2"
authors = ["Dan Burkert <dan@danburkert.com>"]
license = "Apache-2.0"
repository = "https://github.com/danburkert/prost"
documentation = "https://docs.rs/prost-derive"
readme = "README.md"
description = "A Protocol Buffers implementation for the Rust Language."

[lib]
proc_macro = true

[dependencies]
failure = { version = "0.1", default-features = false, features = ["std"] }
itertools = "0.7"
proc-macro2 = "0.2"
quote = "0.4"
syn = { version = "0.12", features = [ "extra-traits" ] }
