[package]
name = "tests-2015"
version = "0.0.0"
authors = [
    "Dan Burkert <dan@danburkert.com>",
    "Tokio Contributors <team@tokio.rs>",
]
publish = false
edition = "2015"

build = "../tests/src/build.rs"

[lib]
doctest = false
path = "../tests/src/lib.rs"

[features]
default = ["edition-2015", "std"]
edition-2015 = []
std = []

[dependencies]
anyhow.workspace = true
bytes.workspace = true
cfg-if.workspace = true
prost = { path = "../prost" }
prost-types = { path = "../prost-types" }
protobuf = { path = "../protobuf" }

[dev-dependencies]
diff.workspace = true
prost-build = { path = "../prost-build" }
tempfile.workspace = true

[build-dependencies]
cfg-if.workspace = true
env_logger.workspace = true
prost-build = { path = "../prost-build" }
protobuf = { path = "../protobuf" }
