[package]
name = "tests-2015"
version = "0.0.0"
authors = ["Dan Burkert <dan@danburkert.com>"]
publish = false
edition = "2015"

build = "../tests/src/build.rs"

[lib]
doctest = false
path = "../tests/src/lib.rs"

[features]
default = ["edition-2015", "std"]
edition-2015 = []
std = ["bytes/std", "prost/std", "prost-types/std", "protobuf/std", "prost-build/std"]

[dependencies]
bytes = { git = "https://github.com/tokio-rs/bytes.git", default-features = false }
cfg-if = "0.1"
prost = { path = "..", default-features = false  }
prost-types = { path = "../prost-types", default-features = false  }
protobuf = { path = "../protobuf", default-features = false  }

[dev-dependencies]
diff = "0.1"
prost-build = { path = "../prost-build", default-features = false }
tempfile = "3"

[build-dependencies]
cfg-if = "0.1"
env_logger = { version = "0.6", default-features = false }
prost-build = { path = "../prost-build", default-features = false  }
protobuf = { path = "../protobuf", default-features = false  }
